server:
  port: 8080

spring:
  cloud:
    gateway:
      routes:
        - id: provider
          uri: http://localhost:8081/
          ## 意思是对http://localhost:8080/provider/**的请求进行拦截，转发至http://localhost:8081/**
          predicates:
            - Path=/provider/**
          ## 表示在将请求发送到下游之前从请求中剥离的路径个数，剥离1个，即http://localhost:8081/**
          filters:
            - StripPrefix=1

        - id: consumer
          uri: http://localhost:8083/
          predicates:
            - Path=/consumer/**
