server:
  port: 8081

spring:
#  cloud:
#    nacos:
#      discovery:
#        # 指定nacos server地址，不用写http://，不配置默认是本机localhost:8848
#        server-addr: localhost:8848
  application:
    # 注册服务的关键因素，注释掉name就不会再注册
    name: my-provider

# 针对此服务设置负载策略
#my-provider:
#  ribbon:
#    NFLoadBalancerRuleClassName: com.gs.provider.config.BalanceWeightRule
